title: Dr. Jiang's Homepage
page-top-title: Dr. Jiang
top-section-bg-text: Intelligent Science and Technology
home-subtitle: Dr. Jiang&ensp;|&ensp;å§œ...
copyright-text: '&copy; MX Jiang 2025. All Rights Reserved.'
